### ISSUE TITLE
[BUG] Mismatch between column names when inserting exercises

### ISSUE THREAD

**Issue by LX6T** [SE310-Team-1/SE310_Fitness_Tracker#37]
Your issue may already be reported!
- [x] I searched on the [issue tracker](../) before creating one and found no duplicate. 
- [x] I have read the code of conduct and agree.

## Expected Behavior
Posting an completed set to the logExerciseSet endpoint should insert an entry into the database and return a success response

## Current Behavior
![image](https://github.com/user-attachments/assets/9834b2bb-99bf-4282-a859-54ad3d9c1c3d)

Server currently complains about 'set' column not existing in the DB 

## Possible Solution
![image](https://github.com/user-attachments/assets/3b3e1c6e-0eab-43c5-8edb-18a9be9e8004)
Fairly sure this is just a typo,  should be checking onConflict with 'sets' not 'set'

## Steps to Reproduce (for bugs)
1. Navigate to Exercises tab
2. Log at least one set of any exercise
3. Click 'Log Workout' (check console for errors)

**Comment by chrisv09** [comment]
Looks good to me!

**Comment by LX6T** [comment]
Issue updated to reflect observed behaviour with latest DB iteration
