### ISSUE TITLE
[Refactor] Refactor backend to use IDs

### ISSUE THREAD

**Issue by Taks07** [SE310-Team-1/SE310_Fitness_Tracker#55]
Please ensure the following for feature requests
- [x] I checked to ensure there aren't other open Pull Requests for the same update/change.

## Is your feature request related to a problem? Please describe.
The endpoints for the backend are very complicated right now, using a lot of route parameters. 
![image](https://github.com/user-attachments/assets/11f827a8-39af-443a-9f22-1b30b7edd2db)

## Describe the solution you'd like
Instead, the only route parameters we should be using are IDs, with any data being sent in the request body. This will probably require rewriting all the controller functions.

## Include a user story to describe why you want this feature
As a future dev working on this project, I want to have simple endpoints so that it is easier to work with them

**Comment by vonner04** [comment]
This will also require refactoring the async responses involving these routes.

EX: 
![image](https://github.com/user-attachments/assets/14e8fc5c-39a6-4c17-a4c1-68d31ffa742c)
