### ISSUE TITLE
[Feature] User-created Exercises

### ISSUE THREAD

**Issue by vonner04** [SE310-Team-1/SE310_Fitness_Tracker#58]
Please ensure the following for feature requests
- [x] I checked to ensure there aren't other open Pull Requests for the same update/change.

## Is your feature request related to a problem? Please describe.
When adding exercise from Today's Workout tab it's hard-coded to Chest Press Machine.

depends on #55 
depends on #57 

## Describe the solution you'd like

Would like to add an exercise based on input and not hard coded.

## Include a user story to describe why you want this feature

.As a gym-goer, I want to put custom names to my exercises so that I can accurately track what exercise I did.

**Comment by vonner04** [comment]
This might require User Account Creation feature to be done first to make the logic for this one a lot easier. [refer to Issue involving User Account creation].

**Comment by Taks07** [comment]
closed by #84
