### ISSUE TITLE
[Feature] Add profile to database

### ISSUE THREAD

**Issue by clen678** [SE310-Team-1/SE310_Fitness_Tracker#61]
Add profile entity and associated fields to the database so that profile data can be stored

## Is your feature request related to a problem? Please describe.
Currently, workout data is not associated to any profile, we want data to be linked to a profile

## Describe the solution you'd like
Add profile entity and associated fields to the database so that profile data can be stored

## Include a user story to describe why you want this feature
As a user
I want to be able to access my own specific workout data
So that I can see my own data

**Comment by Taks07** [comment]
closed by #55
