### ISSUE TITLE
[Feature] Have graph actually reflect exercises

### ISSUE THREAD

**Issue by Taks07** [SE310-Team-1/SE310_Fitness_Tracker#63]
Please ensure the following for feature requests
- [x] I checked to ensure there aren't other open Pull Requests for the same update/change.

## Is your feature request related to a problem? Please describe.
The graph right now is randomly generated. Depends on #55 

## Describe the solution you'd like
The graph should connect to the backend to get the history of exercises, then display this.

## Include a user story to describe why you want this feature
As a user, I want to be able to view my actual exercise progress in a graph, so that I can easily track my workout progress

**Comment by vonner04** [comment]
Are the endpoints setup for this or not yet?

**Comment by Taks07** [comment]
I think so? I believe its just fetching the workouts history, then passing that into the graph. Might need to calculate the score for each workout in between though

**Comment by vonner04** [comment]
Remove muscle group filter and just track the scores from workouts table.
